### PR TITLE
Added some Youtube channels useful for developers

### PR DESCRIPTION
**Pull request by kaushiksriram16**

### CODE REVIEW

**Comment by kaushiksriram16** [comment]
@Ishaan28malik  please check my PR and give hacktober tag and merge accordingly...

**Comment by kaushiksriram16** [comment]
@Ishaan28malik please respond!... hacktober fest will end soon...

**Comment by Ishaan28malik** [comment]
@kaushiksriram16 good work

**Comment by kaushiksriram16** [comment]
Thank you!😊

**Pull request merged**
